apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    app: management
    run: management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: management
    run: management
